### ISSUE TITLE
Rating - numeric or categorical?

### ISSUE THREAD

**Issue by markusnam** [UBC-MDS/chocolate_rating#15]
According to spec, Rating could be from 1.0 to 5.0.
But from the downloaded dataset, it is not that "continuous".
The step is 0.25.
i.e. 1.0, 1.25, 1.5, ...4.5, 4.75, 5.0

Later, we will have to decide whether to go for numeric (regression) or categorical (classification).
One concern from me is that if we go for categorical, it is indeed not pure classification problem as it has ordinality. I am not sure if this "ordinality" would have any impact...

**Comment by eyrexh** [comment]
Vote for numeric since too many target categories(at least 5) will be considered

**Comment by robindhillon1** [comment]
Both make sense. Numeric is obvious but categorical is also valid; it's like the 573 Lab 1 in which area code is categorical. Similar reasoning applies here I think. But yeah numeric seems ideal.

**Comment by LishaGG** [comment]
I also think both make sense, but I lean more towards numeric. If we want to classify rating as categorical, we need to figure out something to make the increment larger so that we won't have so many categories. However, by doing so, it will lose the point of creating a model which can correctly predict the rating. Therefore, numeric would be better.

**Comment by markusnam** [comment]
Cool. Let's treat our target `Rating` as numeric.
